name: Build & Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  DOCKERHUB_SLUG: docker.io/yucatovo/qbittorrentee
  GHCR_SLUG: ghcr.io/yucat-ovo/qbittorrentee

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: ["normal", "iyuu"]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare
        run: |
          if [ ${{ matrix.type }} == "iyuu" ]; then
            echo "SUFFIX=-iyuu" >> "$GITHUB_ENV"
          else
            echo "NORMAL=-normal" >> "$GITHUB_ENV"
          fi

      - name: Docker Meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tags: |
            type=ref,event=branch,suffix=${{ env.SUFFIX }},enable=${{ github.ref_name != github.event.repository.default_branch }}
            type=edge,suffix=${{ env.SUFFIX }},branch=develop
            type=raw,value=latest,suffix=${{ env.SUFFIX }},enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=sha,suffix=${{ env.SUFFIX }}
          labels: |
            org.opencontainers.image.title=qBittorrent-Enhanced-Edition-Docker
            org.opencontainers.image.description=A qBittorrent Enhanced Edition Docker image.
            org.opencontainers.image.vendor=YuCat-OVO

      - name: Rename meta bake definition file
        run: |
          mv "${{ steps.meta.outputs.bake-file }}" "/tmp/bake-meta${{ env.SUFFIX }}.json"

      - name: Upload meta bake definition
        uses: actions/upload-artifact@v4
        with:
          name: bake-meta${{ env.SUFFIX }}${{ env.NORMAL }}
          path: /tmp/bake-meta${{ env.SUFFIX }}${{ env.NORMAL }}.json
          if-no-files-found: error
          retention-days: 1

  build:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        type: ["normal", "iyuu"]
        platform: ["linux/amd64", "linux/arm/v7", "linux/arm64/v8"]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Variable
        id: set_var
        run: |
          if [ ${{ matrix.type }} == "iyuu" ]; then
            echo "SUFFIX=-iyuu" >> "$GITHUB_ENV"
          else
            echo "NORMAL=-normal" >> "$GITHUB_ENV"
          fi

          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> "$GITHUB_ENV"
          echo "ARCH=${platform//linux\//}" >> "$GITHUB_ENV"

          VERSION_GET=$(jq -r '.[0].build' info.json)

          QBEE_TAG=$(jq -r ".[${VERSION_GET}].qbittorrent_enhanced_edition_version" info.json | sed 's/v//')
          QB_TAG=$(jq -r ".[${VERSION_GET}].qbittorrent_version" info.json | sed 's/v//')

          ARCH=${platform//linux\//}
          if [ "${ARCH}" == "amd64" ]; then
              FILE_NAME=$(jq -r ".[${VERSION_GET}].arch.amd64.file_name" info.json)
          elif [ "${ARCH}" == "arm/v7" ]; then
              FILE_NAME=$(jq -r ".[${VERSION_GET}].arch.arm64v8.file_name" info.json)
          elif [ "${ARCH}" == "arm64/v8" ]; then
              FILE_NAME=$(jq -r ".[${VERSION_GET}].arch.armv7.file_name" info.json)
          fi

          echo "QB_TAG=${QB_TAG}" >> "$GITHUB_ENV"
          echo "QBEE_TAG=${QBEE_TAG}" >> "$GITHUB_ENV"
          echo "FILE_NAME=${FILE_NAME}" >> "$GITHUB_ENV"

          git clone -b master https://github.com/devome/dockerfiles.git files
          cp -r files/qbittorrent/root root
          cp -r files/qbittorrent/root2 root2
          ls -al
          ls -al root
          ls -al root2

      - name: Download meta bake definition
        uses: actions/download-artifact@v4
        with:
          name: bake-meta${{ env.SUFFIX }}${{ env.NORMAL }}
          path: /tmp

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--debug"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        id: bake
        uses: docker/bake-action@v4
        env:
          TYPE: ${{ env.TYPE }}
        with:
          files: |
            ./docker-bake.hcl
            /tmp/bake-meta${{ env.SUFFIX }}${{ env.NORMAL }}.json
          targets: image
          set: |
            *.args.QBEE_TAG=${{ env.QBEE_TAG }}
            *.args.FILE_NAME=${{ env.FILE_NAME }}
            *.tags=
            *.platform=${{ matrix.platform }}
            *.cache-from=type=gha,scope=build-${{ env.PLATFORM_PAIR }}
            *.cache-to=type=gha,scope=build-${{ env.PLATFORM_PAIR }}
            *.output=type=image,"name=${{ env.DOCKERHUB_SLUG }},${{ env.GHCR_SLUG }}",push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests${{ env.SUFFIX }}${{ env.NORMAL }}
          digest="${{ fromJSON(steps.bake.outputs.metadata).image['containerimage.digest'] }}"
          touch "/tmp/digests${{ env.SUFFIX }}${{ env.NORMAL }}/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}${{ env.SUFFIX }}${{ env.NORMAL }}
          path: /tmp/digests${{ env.SUFFIX }}${{ env.NORMAL }}/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        type: ["normal", "iyuu"]

    steps:
      - name: Prepare
        run: |
          if [ ${{ matrix.type }} == "iyuu" ]; then
            echo "SUFFIX=-iyuu" >> "$GITHUB_ENV"
          else
            echo "NORMAL=-normal" >> "$GITHUB_ENV"
          fi

      - name: Download meta bake definition
        uses: actions/download-artifact@v4
        with:
          name: bake-meta${{ env.SUFFIX }}${{ env.NORMAL }}
          path: /tmp

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests${{ env.SUFFIX }}${{ env.NORMAL }}
          pattern: digests-*${{ env.SUFFIX }}${{ env.NORMAL }}
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests${{ env.SUFFIX }}${{ env.NORMAL }}
        run: |
          docker buildx imagetools create $(jq -cr '.target."docker-metadata-action".tags | map(select(startswith("${{ env.DOCKERHUB_SLUG }}")) | "-t " + .) | join(" ")' /tmp/bake-meta${{ env.SUFFIX }}${{ env.NORMAL }}.json) \
            $(printf '${{ env.DOCKERHUB_SLUG }}@sha256:%s ' *)
          docker buildx imagetools create $(jq -cr '.target."docker-metadata-action".tags | map(select(startswith("${{ env.GHCR_SLUG }}")) | "-t " + .) | join(" ")' /tmp/bake-meta${{ env.SUFFIX }}${{ env.NORMAL }}.json) \
            $(printf '${{ env.GHCR_SLUG }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          tag=$(jq -r '.target."docker-metadata-action".args.DOCKER_META_VERSION' /tmp/bake-meta${{ env.SUFFIX }}${{ env.NORMAL }}.json)
          docker buildx imagetools inspect ${{ env.DOCKERHUB_SLUG }}:${tag}
          docker buildx imagetools inspect ${{ env.GHCR_SLUG }}:${tag}
